FROM quay.io/redhat-user-workloads/konflux-jbs-pnc-tenant/jvm-build-service-builder-images/ubi7:764d80406b0c67f77b32fc61633caaf70728c4fb
USER 0
WORKDIR /var/workdir
ARG PROXY_URL=""
ENV PROXY_URL=$PROXY_URL
COPY .jbs/run-build.sh /var/workdir
COPY . /var/workdir/workspace/source/
RUN /var/workdir/run-build.sh
FROM quay.io/ncross/hacbs-jvm-build-request-processor:latest AS build-request-processor
USER 0
WORKDIR /var/workdir
COPY --from=0 /var/workdir/ /var/workdir/
RUN /opt/jboss/container/java/run/run-java.sh copy-artifacts --source-path=/var/workdir/workspace/source --deploy-path=/var/workdir/workspace/artifacts
FROM scratch
COPY --from=1 /var/workdir/workspace/artifacts /
